import 'package:flutter/material.dart';

class DarkTheme {
  static ThemeData get theme {
    return ThemeData(
      brightness: Brightness.dark,
      primaryColor: Colors.blueGrey[800],
      scaffoldBackgroundColor: Colors.grey[900],
      colorScheme: ColorScheme.dark(
        primary: const Color(0xffbb86fc),
        onPrimary: Colors.black,
        primaryContainer: const Color(0xff3700b3),
        onPrimaryContainer: Colors.white,
        primaryFixed: const Color(0xff6200ee),
        primaryFixedDim: const Color(0xff3700b3),
        onPrimaryFixed: Colors.white,
        onPrimaryFixedVariant: const Color(0xffbb86fc),
        secondary: const Color(0xff03dac6),
        onSecondary: Colors.black,
        secondaryContainer: const Color(0xff018786),
        onSecondaryContainer: Colors.white,
        secondaryFixed: const Color(0xff03dac6),
        secondaryFixedDim: const Color(0xff018786),
        onSecondaryFixed: Colors.black,
        onSecondaryFixedVariant: const Color(0xff03dac6),
        tertiary: const Color(0xffb00020),
        onTertiary: Colors.white,
        tertiaryContainer: const Color(0xff3700b3),
        onTertiaryContainer: Colors.white,
        tertiaryFixed: const Color(0xffb00020),
        tertiaryFixedDim: const Color(0xff3700b3),
        onTertiaryFixed: Colors.white,
        onTertiaryFixedVariant: const Color(0xffb00020),
        error: const Color(0xffcf6679),
        onError: Colors.black,
        errorContainer: const Color(0xffb00020),
        onErrorContainer: Colors.white,
        surface: const Color(0xff121212),
        onSurface: Colors.white,
        surfaceDim: const Color(0xff1e1e1e),
        surfaceBright: const Color(0xff2c2c2c),
        surfaceContainerLowest: const Color(0xff0f0f0f),
        surfaceContainerLow: const Color(0xff1a1a1a),
        surfaceContainer: const Color(0xff242424),
        surfaceContainerHigh: const Color(0xff2e2e2e),
        surfaceContainerHighest: const Color(0xff383838),
        onSurfaceVariant: const Color(0xffd1d1d1),
        outline: const Color(0xff737373),
        outlineVariant: const Color(0xff8a8a8a),
        shadow: Colors.black,
        scrim: Colors.black,
        inverseSurface: const Color(0xfff5f5f5),
        onInverseSurface: const Color(0xff121212),
        inversePrimary: const Color(0xff6200ee),
        surfaceTint: const Color(0xffbb86fc),
      ),
      cardColor: Colors.grey[800],
      appBarTheme: AppBarTheme(
        backgroundColor: Colors.blueGrey[900],
        elevation: 0,
        iconTheme: IconThemeData(color: Colors.white),
        titleTextStyle: TextStyle(
          color: Colors.white,
          fontSize: 20,
          fontWeight: FontWeight.bold,
        ),
      ),
      textTheme: TextTheme(
        bodyLarge: TextStyle(color: Colors.white70),
        bodyMedium: TextStyle(color: Colors.white60),
        headlineLarge: TextStyle(color: Colors.white, fontSize: 24, fontWeight: FontWeight.bold),
        titleLarge: TextStyle(color: Colors.white70, fontSize: 20, fontWeight: FontWeight.w600),
        bodySmall: TextStyle(color: Colors.white54, fontSize: 12),
        labelLarge: TextStyle(color: Colors.white70, fontSize: 14, fontWeight: FontWeight.w600),
        labelMedium: TextStyle(color: Colors.white60, fontSize: 12, fontWeight: FontWeight.w500),
        labelSmall: TextStyle(color: Colors.white54, fontSize: 10, fontWeight: FontWeight.w400),
        displayLarge: TextStyle(color: Colors.white, fontSize: 32, fontWeight: FontWeight.bold),
        displayMedium: TextStyle(color: Colors.white70, fontSize: 28, fontWeight: FontWeight.w600),
        displaySmall: TextStyle(color: Colors.white60, fontSize: 24, fontWeight: FontWeight.w500),
        headlineMedium: TextStyle(color: Colors.white, fontSize: 22, fontWeight: FontWeight.bold),
        headlineSmall: TextStyle(color: Colors.white70, fontSize: 20, fontWeight: FontWeight.w600),
        titleMedium: TextStyle(color: Colors.white60, fontSize: 18, fontWeight: FontWeight.w500),
        titleSmall: TextStyle(color: Colors.white54, fontSize: 16, fontWeight: FontWeight.w400),
      ),
      buttonTheme: ButtonThemeData(
        buttonColor: Colors.blueGrey[700],
        textTheme: ButtonTextTheme.primary,
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          foregroundColor: Colors.white, backgroundColor: Colors.blueGrey[700],
          textStyle: TextStyle(fontWeight: FontWeight.bold),
        ),
      ),
      iconTheme: IconThemeData(color: Colors.white70),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: Colors.grey[800],
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8.0),
          borderSide: BorderSide.none,
        ),
        hintStyle: TextStyle(color: Colors.white60),
      ),
    );
  }
}